### PR TITLE
Use new fallback config item

### PR DESCRIPTION
**Pull request by Kodikuu**
Needs testing

In Parsec build 150-85, we added a feature to use our virtual display driver to create a fallback display, if the feature is enabled (disabled-by-default). 
This is a better solution that what this project currently does to enable the virtual displays, but I don't have the time to test it myself.

This should reliably create a virtual display to capture, but only if there are no other displays present.

### CODE REVIEW

**Comment by klemens-st** [comment]
I have tested it with Parsec 150-85c:
* `host_virtual_monitors = 1` is ignored, as I understand this is expected because free edition no longer respects this setting
* `host_virtual_monitor_fallback = 1` does not work because there *always is* another display present - Hyper-V display; in my case (Win 11 hypervisor and guest) disabling Hyper-V display in the guest, as the script in this repo does, does not prevent the guest system from detecting a connected virtual display. Uninstalling Hyper-V display in the guest does not help either - it automatically readds itself.

To continue using my VM I had to install another virtual display - [usbmmidd_v2](https://www.amyuni.com/forum/viewtopic.php?t=3030).

**Comment by Kodikuu** [comment]
The original setting should still work at this time.

Quit the Parsec app in the VM entirely (no tray icon, no parsecs.exe) and
add the config line.
After that, you can confirm it's applied by changing any UI setting in the
app; the added config line will stay. For troubleshooting's sake, also
manually change the bitrate or similar to something that can't be normally
set in the UI (e.g; 11Mbps). It will ALSO stay, and the UI will show an
incorrect value (11 is not in its list)

**Comment by klemens-st** [comment]
Thanks, that fixed the issue with `host_virtual_monitors`, wondering if it will survive an update

**Comment by Kodikuu** [comment]
This project relies on the virtual displays, so it will remain. If/When fallback works in the case of these VMs, it may change, but you'll have working fallback

**Comment by Kodikuu** [comment]
Closed until fallback works in cases where the available displays are not capturable

**Pull request closed without merging**
