### PR TITLE
Allow resolution change

### PR DESCRIPTION
**Pull request by PrestonTaylor**
Simple change for setting difference resolutions. 
-Maximum or -Single are required for this to take affect, -Maximum will add other resolutions to the available list inside the OS.

### CODE REVIEW

**Comment by Kodikuu** [comment]
The virtual display driver used by the script handles the actual resolution during use, not this script or Hyper-V.

**Comment by PrestonTaylor** [comment]
@Kodikuu incorrect. Running this command makes changes to the virtual display driver and most importantly the "Maximum" arg allows games to detect that you have multiple resolutions available and unity games won't force set your window size to max.


When using parsec:

Before
image

After
image

**Comment by Kodikuu** [comment]
You're setting the maximum of the HyperV monitor that is supposed to be
inactive during the Parsec stream.

You are not setting anything on the Parsec Virtual Display Adapter with
your command.

Your command only works if your VM isn't working properly. Chances are
you're missing one or two configs in your Parsec config on the VM.

**Comment by Kodikuu** [comment]
This is my Parsec config, as set by the script and modified by Parsec during runtime. If you're missing the bottom two configs, your VM is not set up properly.

image

Then, in my Device Manager, I can see my partitioned GPU, the disabled HyperV adapter, and Parsec Virtual Display Adapter.
The section under Monitors is while connected; There's a basic microsoft display that gets disabled/ignored, and a Parsec virtual display

image

Also while connected, here's the advanced details from Windows' display settings for each of the displays
image
image

And then finally, my resolution dropdown, which allows up to 4K just fine without any tweaking, because the virtual display adapter defines it's own resolutions. Your command only impacts the Hyper-V display that you're not supposed to be using.
image


It _does_ appear that Enhanced Session Mode may need to be on for Parsec's virtual displays to work, despite not using the Hyper-V adapter. Something I'll need to explore

**Pull request closed without merging**
